### ISSUE TITLE
와이어프레임 작성 툴

### ISSUE THREAD

**Issue by KimPra2989** [love1ace/theboys#2]

**Comment by KimPra2989** [comment]
![스크린샷 2024-05-22 111500](https://github.com/love1ace/theboys/assets/106394183/d36b55e2-6714-49a5-b6a1-79fbc60c5ceb)

https://lucid.app/lucidchart/8ae298e8-aee4-4f28-8397-e3ebf937d63e/edit?beaconFlowId=9E60BE60F09814F1&invitationId=inv_3239e8b4-9ebd-4826-807a-13fdbda679fb&page=0_0#

조립식으로 flow 차트 작성이 가능하고, 여러 명이서 작업 가능하고, 결과를 png 등의 이미지 파일로 추출해내는 것도 가능해서 용이한 것 같습니다.

**Comment by sjgaru-dev** [comment]
좋네요, 감사합니다.

**Comment by choesoonoh** [comment]
최고입니다.
